apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kyverno-policies
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: kyverno
    server: https://kubernetes.default.svc
  project: core
  source:
    chart: kyverno-policies
    repoURL: https://kyverno.github.io/kyverno
    targetRevision: v3.8.0
    helm:
      releaseName: kyverno-policies
      values: |
        customLabels:
          cg-devx.cost-allocation.cost-center: platform
          cg-devx.metadata.owner: <GITOPS_REPOSITORY_NAME>-admin
          cg-devx.metadata.service: policy-engine.kyverno-policies
          cg-devx.metadata.chart-version: 3.8.0
          cg-devx.metadata.version: v1.18.0
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true