[tool.poetry]
name = "cgdevxcli"
version = "0.3.0"
description = ""
authors = ["Alexander Ulyanov <alexu@cloudgeometry.io>", "Mikhail Turetskii <mturetsky@cloudgeometry.io>"]
readme = "README.md"
packages = [{ include = "cli" }]

[tool.poetry.scripts]
cgdevxcli = "cli.__main__:entry_point"
build = "cli.build:install"

[tool.poetry.dependencies]
python = ">=3.10,<3.14"
click = "^8.4.1"
cloup = "^3.1.0"
PyInstaller = "^6.21.0"
setuptools = "^82.0.1"
awscli = "^1.45.36"
boto3 = "^1.43.36"
configparser = "^7.2.0"
pyyaml = "^6.0.3"
kubernetes = "^36.0.2"
azure-identity = "^1.25.3"
azure-storage-blob = "^12.30.0"
azure-mgmt-resource = "^25.0.0"
azure-mgmt-authorization = "^4.0.0"
azure-mgmt-dns = "^9.0.0"
azure-mgmt-privatedns = "^1.2.0"
azure-mgmt-containerservice = "^41.3.0"
azure-mgmt-storage = "^25.0.0"
azure-mgmt-subscription = "^3.1.1"
azure-mgmt-compute = "^38.1.0"
gcloud = "^0.18.3"
gitpython = "^3.1.50"
ghrepo = "^0.7.1"
dnspython = "^2.8.0"
hvac = "^2.4.0"
alive-progress = "^3.3.0"
kr8s = "^0.20.15"
google-cloud-storage = "^3.12.0"
google-cloud-dns = "^0.37.0"
google-auth = "^2.55.0"
google-api-python-client = "^2.197.0"
google-cloud-container = "^2.65.0"
anyio = "^4.9"

[tool.poetry.group.dev.dependencies]
flake8 = "^7.3.0"
flake8-class-attributes-order = "^0.3.0"
flake8-docstrings = "^1.7.0"
pydocstyle = "^6.3.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
